server:
  port: 8080



spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.108.196:3306/chuangyue
    username: root
    password: 123456
    hikari:
      max-lifetime: 60000
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true

chuangyue:
  jwt:
    user-secret-key: chuangyue
    user-token-name: authorization
    user-ttl: 7200000
  wechat:
    appid: ${chuangyue.wechat.appid}
    secret: ${chuangyue.wechat.secret}
