server:
  port: 8080



spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.108.196:3306/chuangyue
    username: root
    password: 12345678
    hikari:
      max-lifetime: 60000
  data:
    redis:
      host: 101.43.108.196
      password: 123456
      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      zyp:
        mapper: debug
        service: info
        controller: info

chuangyue:
  jwt:
    user-secret-key: chuangyue
    user-token-name: authorization
    user-ttl: 86400000
    admin-secret-key: chuangyue
    admin-token-name: authorization
    admin-ttl: 86400000
  wechat:
    appid: ${chuangyue.wechat.appid}
    secret: ${chuangyue.wechat.secret}
